{
    'name': 'Student Details',
    'version': '19.0.1.7.1',
    'summary': 'Collect and manage student details with portal access',
    'sequence': 1,
    'category': 'Education',
    'author': 'Ajesh',
    'website': 'http://otomater.com',
    'depends': ['base', 'portal', 'website', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/registration_sequence.xml',
        'views/student_views.xml',
        'views/res_config_settings_views.xml',
        'views/course.xml',
        'views/batch.xml',
        'views/student_attendance_view.xml',
        'views/attendance_whatsapp_views.xml',
        'views/exam_views.xml',
        'views/exam_portal_templates.xml',
        'views/student_portal_templates.xml',
        'views/student_attendance_templates.xml',
        'wizard/manage_coordinators_views.xml',
        'views/fee_structure_views.xml',
        'views/batch_transfer_views.xml',
        'views/enrollment_views.xml',
        'views/attendance_report_wizard_view.xml',
        'views/saas_dashboard_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'student_details_19/static/src/css/student_portal.css',
        ],
        'web.assets_backend': [
            'student_details_19/static/src/css/student_profile.css',
            'student_details_19/static/src/css/saas_dashboard.css',
            'student_details_19/static/src/js/saas_dashboard.js',
            'student_details_19/static/src/xml/saas_dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
