from . import res_config_settings
from . import student
from . import student_attendance1
from . import fee_structure
from . import enrollment
from . import razorpay_payment
from . import batch_transfer
from . import moodle_portal_sync
from . import saas_dashboard
from . import demo_data
